services:
  nginx:
    image: nginx:alpine
    ports:
      - "127.0.0.1:28008:80"
      - "127.0.0.1:28009:443"
    volumes:
      - ../nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
      - ../ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
    networks:
      - leakage-network
    restart: unless-stopped
